
services:
  client:
    image: plantpulse/client
    build: ./plantpulse
    ports:
      - "3000:3000"

  server:
    image: plantpulse/server
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      SECRET_KEY: b&XPYPZgJb4BgTqwo4aQu9lpAhmscrg8JAHwT4&oKDa7okhV6xXLD#fkttx8WLdt
      MONGO_USER: dbuser
      MONGO_PW: i2kjrLCFEkf7o
      MONGODB_URI: mongodb://mongo/plantpulse

  mongo:
    image: plantpulse/db
    build: ./DB
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 4QXdM4SMLUKfuvB
    volumes:
      - ./mongo-data:/data/db/plantpulse
      - ./DB/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js