openapi: '3.0.3'
info:
  title: PlantPulse API
  version: '1.0'
servers:
  - url: https://plantpulse.app/api/v1
paths:
  /users/login:
    post:
      requestBody: 
        'email': 'shookke@gmail.com'
        'password': 'Firefly1#'
      responses:
        '200':
          description: OK
